{% set name = "dython" %}
{% set version = "0.7.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d7a17d214a0a916dffbf39c9e7114fb458f7b0574dab24a301c4dd34188edb2

build:
  number: 0
  noarch: python
  script:
    - echo $PKG_VERSION > VERSION  # [not win]
    - cp ${RECIPE_DIR}/DESCRIPTION.md .  # [not win]
    - echo %PKG_VERSION% > VERSION  # [win]
    - copy %RECIPE_DIR%\DESCRIPTION.md .  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - matplotlib >=3.6.0
    - numpy >=1.23.0
    - pandas >=1.4.2
    - psutil >=5.9.1
    - python >=3.6
    - scikit-learn >=0.24.2
    #- scikit-plot >=0.3.7
    - scipy >=1.7.1
    - seaborn >=0.12.0

test:
  imports:
    - dython
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://shakedzy.xyz/dython
  summary: A set of data tools in Python
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: http://shakedzy.xyz/dython/getting_started/installation/
  dev_url: http://shakedzy.xyz/dython/modules/data_utils/

extra:
  recipe-maintainers:
    - sarthakpati
